name = "Create Server"
author = "OwO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85cd87852d49a613a647482df09a24280c5079501e0182e3ade42d0605241c6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
