name = "Create Server"
author = "OwO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7b1ecb9f497d73692fc6089d6e9983bd3d27c531bb699e5b35029aa9a8f54da"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
