name = "Create Server"
author = "OwO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3725ab018ff275681502cb3bbebea170539669df50b216faeaaa0f8755331fbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
